baseURL = 'https://roneo.itcouldbewor.se/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = 'Barnes Bend is our community in Nashville'
  metaDescription = "Find Homeowners Documents, join our social media communities, ask questions to the property manager"

[params.favicon]
  appleTouchIcon = "/meta/apple-touch-icon.png"
  icon32 = "/meta/favicon-32x32.png"
  icon16 = "/meta/favicon-16x16.png"
  manifest = "/meta/site.webmanifest"
  maskIcon = "/meta/safari-pinned-tab.svg"

# Languages
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"

[Languages.fr]
languageName = "fr"
languageCode = "fr-fr"
contentDir = "content/fr"
weight = 2
mark = "FR"


[taxonomies]
  category= "theme"
  scene = "scenes"
